import { Metadata } from "next"

export const metadata : Metadata= {
    title: {
        absolute:"",
        default:" Next.js Tutorial - Codevalution",
        template:"%s | Codevalution"
    },
    description:"Generated by Next.js",
}


export default function About(){
    return <h1>About me</h1>

}